export const  Products = [

    
        
          {
            "id": 1,
            "name": "Men's Casual Shirt",
            "brand": "FashionCo",
            "price": 29.99,
            "description": "Stylish and comfortable casual shirt for men.",
            "category": "Men",
            "image": "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8bWVucyUyMGNhc3VhbCUyMHRzaGlydHxlbnwwfHwwfHx8MA%3D%3D&auto=format&fit=crop&w=500&q=60",
            "stock": 50,
            "colors": ["Black", "White", "Blue", "Gray"],
             "sizes": ["S", "M", "L", "XL"],
            "rating": 4,
            "best_seller": true,
      "longDescription": "The Men's Classic T-Shirt is a wardrobe staple. Its classic design and comfortable fit make it perfect for everyday wear. Made from high-quality cotton, this t-shirt is soft and breathable, keeping you cool and comfortable all day long. Available in multiple colors and sizes.",
      "material": "100% Cotton"
          },
          {
            "id": 2,
            "name": "Women's Floral Dress",
            "brand": "Fashionista",
            "price": 39.99,
            "description": "Elegant and fashionable floral dress for women.",
            "category": "Women",
            "image": "https://images.unsplash.com/photo-1478146896981-b80fe463b330?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8V29tZW4ncyUyMEZsb3JhbCUyMERyZXNzfGVufDB8fDB8fHww&auto=format&fit=crop&w=500&q=60",
            "stock": 30,
            "rating": 4,
            "best_seller": false,
            "colors": ["White Floral", "Red Floral", "Blue Floral"],
            "sizes": ["S", "M", "L", "XL"],
            "longDescription": "Step into spring with our Women's Floral Dress. This beautiful dress features a flattering fit and a charming floral pattern. The lightweight fabric is perfect for warm weather, making it ideal for outdoor events and gatherings. Available in various floral prints and sizes.",
            "material": "Polyester"
          },
          {
            "id": 3,
            "name": "Children's T-shirt",
            "brand": "KidzWear",
            "price": 14.99,
            "description": "Cute and colorful t-shirt for children.",
            "category": "Children",
            "image": "https://img.freepik.com/free-photo/front-view-cute-child-boy-white-t-shirt-yellow-jeans-holding-green-skateboard-blue-floor_179666-1008.jpg?size=626&ext=jpg",
            "stock": 100,
            "rating": 5,
            "best_seller": true,
            "colors": ["Blue", "Dark Blue"],
      "sizes": ["2T", "3T", "4T", "5T"],
      "longDescription": "Our Kids' Denim Shorts are a must-have for any little fashionista. These shorts are made from high-quality denim that can withstand active play and rough adventures. They feature a comfortable fit and trendy design. Available in different shades of blue.",
      "material": "Denim (100% Cotton)"
          },
          {
            "id": 4,
            "name": "Men's Jeans",
            "brand": "DenimKraft",
            "price": 49.99,
            "description": "High-quality denim jeans for men.",
            "category": "Men",
            "image": "https://sslimages.shoppersstop.com/sys-master/images/ha0/h38/27837776691230/AW22ROCKSTAR_TINT.jpg_230Wx334H",
            "stock": 25,
            "rating": 3,
            "best_seller": false,
            "colors": ["Black", "White", "Blue", "Gray"],
      "sizes": ["S", "M", "L", "XL"],
      "longDescription": "The Men's Classic T-Shirt is a wardrobe staple. Its classic design and comfortable fit make it perfect for everyday wear. Made from high-quality cotton, this t-shirt is soft and breathable, keeping you cool and comfortable all day long. Available in multiple colors and sizes.",
      "material": "100% Cotton"
          },
          {
            "id": 5,
            "name": "Women's Formal Blouse",
            "brand": "ChicStyle",
            "price": 34.99,
            "description": "Sophisticated formal blouse for women.",
            "category": "Women",
            "image": "https://sslimages.shoppersstop.com/sys-master/images/hb6/ha7/29743515402270/S23INITP01251_BLUE.jpg_230Wx334H",
            "stock": 75,
            "rating": 4,
            "best_seller": true,
            "longDescription": "Step into spring with our Women's Floral Dress. This beautiful dress features a flattering fit and a charming floral pattern. The lightweight fabric is perfect for warm weather, making it ideal for outdoor events and gatherings. Available in various floral prints and sizes.",
            "material": "Polyester",
            "colors": ["White Floral", "Red Floral", "Blue Floral"],
            "sizes": ["S", "M", "L", "XL"],
          },
          {
            "id": 6,
            "name": "Children's Hoodie",
            "brand": "KidzWear",
            "price": 24.99,
            "description": "Warm and comfortable hoodie for children.",
            "category": "Children",
            "image": "https://sslimages.shoppersstop.com/sys-master/images/h07/h36/27960942788638/A22710GSHRT06_PINK.jpg_230Wx334H",
            "stock": 60,
            "rating": 4,
            "best_seller": false,
            "sizes": ["2T", "3T", "4T", "5T"],
            "longDescription": "Our Kids' Denim Shorts are a must-have for any little fashionista. These shorts are made from high-quality denim that can withstand active play and rough adventures. They feature a comfortable fit and trendy design. Available in different shades of blue.",
            "material": "Denim (100% Cotton)",
            "colors": ["Blue", "Dark Blue"],
          },
          {
            "id": 7,
            "name": "Men's Polo Shirt",
            "brand": "FashionCo",
            "price": 19.99,
            "description": "Classic polo shirt for men.",
            "category": "Men",
            "image": "https://sslimages.shoppersstop.com/sys-master/images/h1c/he7/27638478536734/S22MSH01BB225BL_BLACK.jpg_230Wx334H",
            "stock": 40,
            "rating": 4,
            "best_seller": false,
            "colors": ["Black", "White", "Blue", "Gray"],
      "sizes": ["S", "M", "L", "XL"],
      "longDescription": "The Men's Classic T-Shirt is a wardrobe staple. Its classic design and comfortable fit make it perfect for everyday wear. Made from high-quality cotton, this t-shirt is soft and breathable, keeping you cool and comfortable all day long. Available in multiple colors and sizes.",
      "material": "100% Cotton"
          },
          {
            "id": 8,
            "name": "Women's Casual Shorts",
            "brand": "Fashionista",
            "price": 29.99,
            "description": "Comfortable and trendy casual shorts for women.",
            "category": "Women",
            "image": "https://sslimages.shoppersstop.com/sys-master/images/ha3/h05/27614528077854/S22507BW165_SAGE.jpg_230Wx334H",
            "stock": 35,
            "rating": 4,
            "best_seller": true,
            "longDescription": "Step into spring with our Women's Floral Dress. This beautiful dress features a flattering fit and a charming floral pattern. The lightweight fabric is perfect for warm weather, making it ideal for outdoor events and gatherings. Available in various floral prints and sizes.",
            "material": "Polyester",          "colors": ["White Floral", "Red Floral", "Blue Floral"],
            "sizes": ["S", "M", "L", "XL"],
          },
          {
            "id": 9,
            "name": "Children's Denim Jacket",
            "brand": "KidzWear",
            "price": 39.99,
            "description": "Stylish denim jacket for children.",
            "category": "Children",
            "image": "https://sslimages.shoppersstop.com/sys-master/images/h89/h4d/27784324743198/A22710BJKT049_MID_STONE.jpg_230Wx334H",
            "stock": 50,
            "rating": 5,
            "best_seller": false,
            "sizes": ["2T", "3T", "4T", "5T"],
            "longDescription": "Our Kids' Denim Shorts are a must-have for any little fashionista. These shorts are made from high-quality denim that can withstand active play and rough adventures. They feature a comfortable fit and trendy design. Available in different shades of blue.",
            "material": "Denim (100% Cotton)",
            "colors": ["Blue", "Dark Blue"],
          },
          {
            "id": 10,
            "name": "Men's Hooded Sweatshirt",
            "brand": "DenimKraft",
            "price": 39.99,
            "description": "Warm and stylish hooded sweatshirt for men.",
            "category": "Men",
            "image": "https://sslimages.shoppersstop.com/sys-master/images/h9e/h9e/30021313331230/S23M-WRSWETN224_STEEL_GREY.jpg_230Wx334H",
            "stock": 20,
            "rating": 3,
            "best_seller": true,
            "colors": ["Black", "White", "Blue", "Gray"],
      "sizes": ["S", "M", "L", "XL"],
      "longDescription": "The Men's Classic T-Shirt is a wardrobe staple. Its classic design and comfortable fit make it perfect for everyday wear. Made from high-quality cotton, this t-shirt is soft and breathable, keeping you cool and comfortable all day long. Available in multiple colors and sizes.",
      "material": "100% Cotton"
          },
          {
            "id": 11,
            "name": "Women's Maxi Dress",
            "brand": "ChicStyle",
            "price": 49.99,
            "description": "Elegant and flowing maxi dress for women.",
            "category": "Women",
            "image": "https://sslimages.shoppersstop.com/sys-master/images/h53/hb3/27541506588702/S22LAN28076146_MULTI.jpg_230Wx334H",
            "stock": 25,
            "rating": 5,
            "best_seller": false,
            "longDescription": "Step into spring with our Women's Floral Dress. This beautiful dress features a flattering fit and a charming floral pattern. The lightweight fabric is perfect for warm weather, making it ideal for outdoor events and gatherings. Available in various floral prints and sizes.",
            "material": "Polyester",
            "colors": ["White Floral", "Red Floral", "Blue Floral"],
            "sizes": ["S", "M", "L", "XL"],
          },
          {
            "id": 12,
            "name": "Children's Graphic T-shirt",
            "brand": "KidzWear",
            "price": 14.99,
            "description": "Fun and colorful graphic t-shirt for children.",
            "category": "Children",
            "image": "https://sslimages.shoppersstop.com/sys-master/images/h07/h71/28964593860638/BKTS22688WHITE_WHITE.jpg_230Wx334H",
            "stock": 80,
            "rating": 4,
            "best_seller": true,
            "sizes": ["2T", "3T", "4T", "5T"],
            "longDescription": "Our Kids' Denim Shorts are a must-have for any little fashionista. These shorts are made from high-quality denim that can withstand active play and rough adventures. They feature a comfortable fit and trendy design. Available in different shades of blue.",
            "material": "Denim (100% Cotton)",
            "colors": ["Blue", "Dark Blue"],
          },
          {
            "id": 13,
            "name": "Men's Plaid Shirt",
            "brand": "FashionCo",
            "price": 29.99,
            "description": "Trendy plaid shirt for men.",
            "category": "Men",
            "image": "https://sslimages.shoppersstop.com/sys-master/images/h11/ha0/28637771071518/A21SEL233324603_WHITE.jpg_230Wx334H",
            "stock": 45,
            "rating": 4,
            "best_seller": false,
            "colors": ["Black", "White", "Blue", "Gray"],
      "sizes": ["S", "M", "L", "XL"],
      "longDescription": "The Men's Classic T-Shirt is a wardrobe staple. Its classic design and comfortable fit make it perfect for everyday wear. Made from high-quality cotton, this t-shirt is soft and breathable, keeping you cool and comfortable all day long. Available in multiple colors and sizes.",
      "material": "100% Cotton"
          },
          {
            "id": 14,
            "name": "Women's Skinny Jeans",
            "brand": "Fashionista",
            "price": 39.99,
            "description": "Modern and stylish skinny jeans for women.",
            "category": "Women",
            "image": "https://sslimages.shoppersstop.com/sys-master/images/hbb/hfc/29169269375006/A22KRSKLCL104_BLACK.jpg_230Wx334H",
            "stock": 60,
            "rating": 4,
            "best_seller": true,
            "longDescription": "Step into spring with our Women's Floral Dress. This beautiful dress features a flattering fit and a charming floral pattern. The lightweight fabric is perfect for warm weather, making it ideal for outdoor events and gatherings. Available in various floral prints and sizes.",
            "material": "Polyester",
            "colors": ["White Floral", "Red Floral", "Blue Floral"],
            "sizes": ["S", "M", "L", "XL"],
          },
          {
            "id": 15,
            "name": "Children's Summer Dress",
            "brand": "KidzWear",
            "price": 19.99,
            "description": "Light and comfortable summer dress for children.",
            "category": "Children",
            "image": "https://sslimages.shoppersstop.com/sys-master/images/h21/h50/30130176032798/S23K-JGFRKN026_LAVENDER.jpg_230Wx334H",
            "stock": 70,
            "rating": 3,
            "best_seller": false,
            "sizes": ["2T", "3T", "4T", "5T"],
            "longDescription": "Our Kids' Denim Shorts are a must-have for any little fashionista. These shorts are made from high-quality denim that can withstand active play and rough adventures. They feature a comfortable fit and trendy design. Available in different shades of blue.",
            "material": "Denim (100% Cotton)",
            "colors": ["Blue", "Dark Blue"],
          },
          {
            "id": 16,
            "name": "Men's V-neck Sweater",
            "brand": "DenimKraft",
            "price": 34.99,
            "description": "Classic and cozy V-neck sweater for men.",
            "category": "Men",
            "image": "https://sslimages.shoppersstop.com/sys-master/images/hbd/hf4/26531196665886/A21LDHMSWT007BL_RUST.jpg_230Wx334H",
            "stock": 30,
            "rating": 4,
            "best_seller": true,
            "colors": ["Black", "White", "Blue", "Gray"],
      "sizes": ["S", "M", "L", "XL"],
      "longDescription": "The Men's Classic T-Shirt is a wardrobe staple. Its classic design and comfortable fit make it perfect for everyday wear. Made from high-quality cotton, this t-shirt is soft and breathable, keeping you cool and comfortable all day long. Available in multiple colors and sizes.",
      "material": "100% Cotton"
          },
          {
            "id": 17,
            "name": "Women's Knit Cardigan",
            "brand": "ChicStyle",
            "price": 44.99,
            "description": "Versatile and warm knit cardigan for women.",
            "category": "Women",
            "image": "https://sslimages.shoppersstop.com/sys-master/images/hc3/h7b/28238793211934/A22346PW229_BEIGE.jpg_230Wx334H",
            "stock": 40,
            "rating": 5,
            "best_seller": false,
            "longDescription": "Step into spring with our Women's Floral Dress. This beautiful dress features a flattering fit and a charming floral pattern. The lightweight fabric is perfect for warm weather, making it ideal for outdoor events and gatherings. Available in various floral prints and sizes.",
            "material": "Polyester",
            "colors": ["White Floral", "Red Floral", "Blue Floral"],
            "sizes": ["S", "M", "L", "XL"],
          },
          {
            "id": 18,
            "name": "Children's Puffer Jacket",
            "brand": "KidzWear",
            "price": 39.99,
            "description": "Cozy and stylish puffer jacket for children.",
            "category": "Children",
            "image": "https://sslimages.shoppersstop.com/sys-master/images/hfd/h3d/28974869872670/A22JK07221005_BLACK.jpg_230Wx334H",
            "stock": 55,
            "rating": 4,
            "best_seller": true,
            "sizes": ["2T", "3T", "4T", "5T"],
            "longDescription": "Our Kids' Denim Shorts are a must-have for any little fashionista. These shorts are made from high-quality denim that can withstand active play and rough adventures. They feature a comfortable fit and trendy design. Available in different shades of blue.",
            "material": "Denim (100% Cotton)",
            "colors": ["Blue", "Dark Blue"],
          },
          {
            "id": 19,
            "name": "Men's Cargo Shorts",
            "brand": "FashionCo",
            "price": 24.99,
            "description": "Durable and practical cargo shorts for men.",
            "category": "Men",
            "image": "https://sslimages.shoppersstop.com/sys-master/images/hb7/h87/28403541704734/A22TIPNGSHJPBK_BLACK.jpg_230Wx334H",
            "stock": 50,
            "rating": 3,
            "best_seller": false,
            "colors": ["Black", "White", "Blue", "Gray"],
      "sizes": ["S", "M", "L", "XL"],
      "longDescription": "The Men's Classic T-Shirt is a wardrobe staple. Its classic design and comfortable fit make it perfect for everyday wear. Made from high-quality cotton, this t-shirt is soft and breathable, keeping you cool and comfortable all day long. Available in multiple colors and sizes.",
      "material": "100% Cotton"
          },
          {
            "id": 20,
            "name": "Women's Ruffled Blouse",
            "brand": "Fashionista",
            "price": 34.99,
            "description": "Charming and stylish ruffled blouse for women.",
            "category": "Women",
            "image": "https://sslimages.shoppersstop.com/sys-master/images/h99/h80/27427834920990/JAS22J0216_GREEN.jpg_230Wx334H",
            "stock": 65,
            "rating": 4,
            "best_seller": true,
            "longDescription": "Step into spring with our Women's Floral Dress. This beautiful dress features a flattering fit and a charming floral pattern. The lightweight fabric is perfect for warm weather, making it ideal for outdoor events and gatherings. Available in various floral prints and sizes.",
            "material": "Polyester",
            "colors": ["White Floral", "Red Floral", "Blue Floral"],
            "sizes": ["S", "M", "L", "XL"],
          },
          {
            "id": 21,
            "name": "Children's Denim Shorts",
            "brand": "KidzWear",
            "price": 19.99,
            "description": "Trendy and comfortable denim shorts for children.",
            "category": "Children",
            "image": "https://sslimages.shoppersstop.com/sys-master/images/hab/h22/27127380443166/S22710GSHRT009_MID_STONE.jpg_230Wx334H",
            "stock": 75,
            "rating": 5,
            "best_seller": false,
            "sizes": ["2T", "3T", "4T", "5T"],
            "longDescription": "Our Kids' Denim Shorts are a must-have for any little fashionista. These shorts are made from high-quality denim that can withstand active play and rough adventures. They feature a comfortable fit and trendy design. Available in different shades of blue.",
            "material": "Denim (100% Cotton)",
            "colors": ["Blue", "Dark Blue"],
          },
          {
            "id": 22,
            "name": "Men's Checked Shirt",
            "brand": "FashionCo",
            "price": 29.99,
            "description": "Classic and versatile checked shirt for men.",
            "category": "Men",
            "image": "https://sslimages.shoppersstop.com/sys-master/images/he5/h22/29307145289758/S23IMSTSS23001_CHECKS.jpg_230Wx334H",
            "stock": 30,
            "rating": 4,
            "best_seller": true,
            "colors": ["Black", "White", "Blue", "Gray"],
      "sizes": ["S", "M", "L", "XL"],
      "longDescription": "The Men's Classic T-Shirt is a wardrobe staple. Its classic design and comfortable fit make it perfect for everyday wear. Made from high-quality cotton, this t-shirt is soft and breathable, keeping you cool and comfortable all day long. Available in multiple colors and sizes.",
      "material": "100% Cotton"
          },
          {
            "id": 23,
            "name": "Women's A-line Skirt",
            "brand": "ChicStyle",
            "price": 39.99,
            "description": "Flattering and chic A-line skirt for women.",
            "category": "Women",
            "image": "https://sslimages.shoppersstop.com/sys-master/images/h07/h8f/29409090142238/S23507DENSK312_WHITE.jpg_230Wx334H",
            "stock": 45,
            "rating": 4,
            "best_seller": false,
            "longDescription": "Step into spring with our Women's Floral Dress. This beautiful dress features a flattering fit and a charming floral pattern. The lightweight fabric is perfect for warm weather, making it ideal for outdoor events and gatherings. Available in various floral prints and sizes.",
            "material": "Polyester",
            "colors": ["White Floral", "Red Floral", "Blue Floral"],
            "sizes": ["S", "M", "L", "XL"],
          },
          {
            "id": 24,
            "name": "Children's Cartoon Pajamas",
            "brand": "KidzWear",
            "price": 24.99,
            "description": "Adorable and cozy cartoon pajamas for children.",
            "category": "Children",
            "image": "https://sslimages.shoppersstop.com/sys-master/images/ha7/h0a/29713468194846/A23STSBBSLW320_YELLOW.jpg_230Wx334H",
            "stock": 90,
            "rating": 4,
            "best_seller": true,
            "sizes": ["2T", "3T", "4T", "5T"],
            "longDescription": "Our Kids' Denim Shorts are a must-have for any little fashionista. These shorts are made from high-quality denim that can withstand active play and rough adventures. They feature a comfortable fit and trendy design. Available in different shades of blue.",
            "material": "Denim (100% Cotton)",
            "colors": ["Blue", "Dark Blue"],
          },
          {
            "id": 25,
            "name": "Men's Crew Neck Sweater",
            "brand": "DenimKraft",
            "price": 34.99,
            "description": "Classic and comfortable crew neck sweater for men.",
            "category": "Men",
            "image": "https://sslimages.shoppersstop.com/sys-master/images/hc6/h9c/28525579501598/A22STSW504DRNY_NAVY.jpg_230Wx334H",
            "stock": 25,
            "rating": 3,
            "best_seller": false,
            "colors": ["Black", "White", "Blue", "Gray"],
      "sizes": ["S", "M", "L", "XL"],
      "longDescription": "The Men's Classic T-Shirt is a wardrobe staple. Its classic design and comfortable fit make it perfect for everyday wear. Made from high-quality cotton, this t-shirt is soft and breathable, keeping you cool and comfortable all day long. Available in multiple colors and sizes.",
      "material": "100% Cotton"
          },
          {
            "id": 26,
            "name": "Women's Striped T-shirt",
            "brand": "Fashionista",
            "price": 19.99,
            "description": "Casual and trendy striped t-shirt for women.",
            "category": "Women",
            "image": "https://sslimages.shoppersstop.com/sys-master/images/had/h01/30030932017182/S23COV6UB2240WT_WHITE.jpg_230Wx334H",
            "stock": 55,
            "rating": 4,
            "best_seller": true,
            "longDescription": "Step into spring with our Women's Floral Dress. This beautiful dress features a flattering fit and a charming floral pattern. The lightweight fabric is perfect for warm weather, making it ideal for outdoor events and gatherings. Available in various floral prints and sizes.",
            "material": "Polyester",
            "colors": ["White Floral", "Red Floral", "Blue Floral"],
            "sizes": ["S", "M", "L", "XL"],
          },
          {
            "id": 27,
            "name": "Children's Overalls",
            "brand": "KidzWear",
            "price": 29.99,
            "description": "Adorable and practical overalls for children.",
            "category": "Children",
            "image": "https://sslimages.shoppersstop.com/sys-master/images/h4b/h1a/15705037045790/VA034VAR2205035_Pink.jpg_230Wx334H",
            "stock": 40,
            "rating": 5,
            "best_seller": false,
            "sizes": ["2T", "3T", "4T", "5T"],
            "longDescription": "Our Kids' Denim Shorts are a must-have for any little fashionista. These shorts are made from high-quality denim that can withstand active play and rough adventures. They feature a comfortable fit and trendy design. Available in different shades of blue.",
            "material": "Denim (100% Cotton)",
            "colors": ["Blue", "Dark Blue"],
          },
          {
            "id": 28,
            "name": "Men's Chino Pants",
            "brand": "FashionCo",
            "price": 34.99,
            "description": "Classic and versatile chino pants for men.",
            "category": "Men",
            "image": "https://sslimages.shoppersstop.com/sys-master/images/hcb/hd4/30386087264286/S23CPNTKHAKI136_KHAKI.jpg_230Wx334H",
            "stock": 35,
            "rating": 4,
            "best_seller": true,
            "colors": ["Black", "White", "Blue", "Gray"],
      "sizes": ["S", "M", "L", "XL"],
      "longDescription": "The Men's Classic T-Shirt is a wardrobe staple. Its classic design and comfortable fit make it perfect for everyday wear. Made from high-quality cotton, this t-shirt is soft and breathable, keeping you cool and comfortable all day long. Available in multiple colors and sizes.",
      "material": "100% Cotton"
          },
          {
            "id": 29,
            "name": "Women's Off-Shoulder Top",
            "brand": "ChicStyle",
            "price": 24.99,
            "description": "Stylish and trendy off-shoulder top for women.",
            "category": "Women",
            "image": "https://sslimages.shoppersstop.com/sys-master/images/hcd/h5f/26498157445150/A21ZINKT02321_MULTI.jpg_230Wx334H",
            "stock": 50,
            "rating": 4,
            "best_seller": false,
            "longDescription": "Step into spring with our Women's Floral Dress. This beautiful dress features a flattering fit and a charming floral pattern. The lightweight fabric is perfect for warm weather, making it ideal for outdoor events and gatherings. Available in various floral prints and sizes.",
            "material": "Polyester",
            "colors": ["White Floral", "Red Floral", "Blue Floral"],
            "sizes": ["S", "M", "L", "XL"],
          },

      
      

]